import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Addition (+5):", arr + 5)
print("Subtraction (-5):", arr - 5)
print("Multiplication (*2):", arr * 2)
print("Division (/2):", arr / 2)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("First Element:", arr[0])
print("Slice (1 to 3):", arr[1:4])
print("Sorted Array:", np.sort(arr))